### ISSUE TITLE
Weird sizing issues when dragging table headers

### ISSUE THREAD

**Issue by offirgolan** [jgwhite/ember-sortable#101]
Hi there! 

Im trying to use this library in [ember-light-table](https://github.com/offirgolan/ember-light-table) to provide draggable column support but I'm running into some weird issue when dragging.

![draggable-columns](https://cloud.githubusercontent.com/assets/575938/17226126/bade3286-54bc-11e6-831f-12852ee47d42.gif)

> As far as I know, it's like it adds the width of a column when you start to drag a column (i.e. if you have 3 columns it places the first and the second correctly but the third in the place of a fourth column when you drag one). I was looking at the update method in the sortable-group component but I haven't found the problem yet.

>I also removed the CSS of ember-light-table to be sure it wasn't because of it but the problem still persists. - @HenryVonfire

There is a PR open offirgolan/ember-light-table#109 with a branch you are welcome to checkout and test out. Any help here would be appreciated.

**Comment by jgwhite** [comment]
Hi @offirgolan. Really sorry for the slow reply! Something is up with my GitHub notifications, I think half of them may have been going to a defunct email address.

Will take a look now.

**Comment by offirgolan** [comment]
No worries! Thanks for taking the time to investigate 😁

**Comment by jgwhite** [comment]
I gave it a shot. See https://github.com/offirgolan/ember-light-table/pull/143 for detailed answer.

**Comment by offirgolan** [comment]
@jgwhite gonna go ahead an close this issue. Thanks again for all your time!
