### ISSUE TITLE
Seeking new maintainer

### ISSUE THREAD

**Issue by jgwhite** [jgwhite/ember-sortable#108]
I’ve loved working on this project (and I’m very happy that it’s proved useful to the community) but the time has come to hand over the reins.

If you’re interested in taking over maintenance and development of ember-sortable please let me know here. I’ll remain an active contributor and do my utmost to make the handover frictionless.

**Comment by acburdine** [comment]
@jgwhite I could devote some time to this 😄

**Comment by jgwhite** [comment]
@acburdine thanks so much for responding. I’ve invited you to be a collaborator on the repo and the package on NPM.

The priority tasks are:

- [Solve Ember 2.10 test suite incompatiblity](https://github.com/jgwhite/ember-sortable/issues/109)
- [Land the autoscroll PR](https://github.com/jgwhite/ember-sortable/pull/104)
- [Land the test helper fix PR](https://github.com/jgwhite/ember-sortable/pull/106)

If you’ve the cycles to dig into one or more of these, that would be terrific.
