### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by tim-evans** [jgwhite/ember-sortable#110]
[sortable-mixin](https://github.com/jgwhite/ember-sortable/blob/master/addon/mixins/sortable-item.js#L299) doesn't clean up its `primeDrag` method every time, resulting in ember-sortable retaining memory.

The leak happens specifically when a drag action is started, but never completed.

We're seeing ~9Mb of memory being retained in our test suite by this method not being cleaned up completely.

**Comment by jgwhite** [comment]
Good spot! Does it look like it'll be easy to patch?

**Comment by tim-evans** [comment]
I doesn't look to bad. We'll need to maintain a reference to this handler and `$(window).off` it in the `willDestroyElement` hook 😉

**Comment by acburdine** [comment]
@tim-evans do you have time to create a fix for this? Otherwise I can create a fix and get it in version 1.9 😄

**Comment by tim-evans** [comment]
I totally can!
