### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by estshy** [jgwhite/ember-sortable#115]
This component has low performance (especially on mobile) because the touchdown and mousedown handlers are neither debounced nor throttled. In addition events are actually attached to each element of the list instead of being delegated to sortable group. 

To make it possible to attach mousedown and allow people to drag items, dragging should be default prevented only after moving it by let's say 10px otherwise custom events handlers inside sortable-item are broken on mobile (touchstart has higher precedence than click and touchdown).

**Comment by scottmessinger** [comment]
We'd love to see a PR for this! If you need any help, let us know!

**Comment by jgwhite** [comment]
Agreed. All the proposed improvements sound great and I would love to see them come to fruition. Perhaps we could do smart stuff with the capture phase too?

**Comment by estshy** [comment]
@scottmessinger  @jgwhite I've improved the performance of dragging (https://github.com/jgwhite/ember-sortable/pull/118). I will try to focus on the remaining issues when I will find more time.

**Comment by jgwhite** [comment]
@estshy awesome, many thanks. Someone will review your PR soon.

**Comment by scottmessinger** [comment]
Since #118 has been merged, I'm going to close this for now. Thanks @estshy for the PR!!!
