### ISSUE TITLE
Autoscroll reposition bugs

### ISSUE THREAD

**Issue by edeis53** [jgwhite/ember-sortable#116]
https://github.com/jgwhite/ember-sortable/pull/104
@tim-evans 
Issue with autoscroll merge. Create a list of 100 items or so, scroll down to near the bottom. Grab and item to sort. Scroll up a bit and try sorting another item, the scroll position automatically jumps to the position of the last object that was moved.

Also autoscroll to the top of the screen doesn't seem to work. Only to bottom.

**Comment by tim-evans** [comment]
Thanks for the repro. I think I know exactly what's going wrong

**Comment by tim-evans** [comment]
I tried to reproduce this using the dummy app, but cannot. Could you provide a working reproduction for this? This may be the code playing poorly with your configuration.

**Comment by jgwhite** [comment]
Thanks for jumping on this so quick @tim-evans

**Comment by edeis53** [comment]
I made a fresh ember to reproduce. On a fresh install ember-sortable runs fine. Turns out there is a conflict with semantic-ui-ember. Good hint on the configuration issue. You can reproduce the error here: https://github.com/edeis53/ember-sortable-scrollbug.git

**Comment by tim-evans** [comment]
I can reproduce now. I'll try to dig into what's going on.
