### ISSUE TITLE
Ember-sortable is not compatible with WYSIWYG elements

### ISSUE THREAD

**Issue by remithomas** [jgwhite/ember-sortable#117]
I can create a sortable list of WYSIWYG elements but when I re-order the list, my last element lose his content.
Is Ember-sortable is compatible ? 

ps: I use tinyMCE

**Comment by acburdine** [comment]
@remithomas I'm not sure I understand what your issue is here 😕 Can you please provide a reproduction case or maybe a gif screenshot? That would go a long way to help me understand the issue and possibly how to fix it :)
