### ISSUE TITLE
Importing acceptance helpers not working.

### ISSUE THREAD

**Issue by alexparker** [jgwhite/ember-sortable#121]
I've tried importing exactly as described in the README.md and also tried importing directly into the acceptance test but can't seem to find the right path to include the modules. Here are my set of packages: 

  "engines": {
    "node": ">= 0.12.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-cli": "2.9.1",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-emblem": "0.4.0",
    "ember-cli-htmlbars": "^1.0.10",
    "ember-cli-htmlbars-inline-precompile": "^0.3.3",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jshint": "^1.0.4",
    "ember-cli-mirage": "0.2.3",
    "ember-cli-moment-shim": "1.1.0",
    "ember-cli-qunit": "^3.0.1",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-stylus": "1.0.6",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-composable-helpers": "1.0.0",
    "ember-cp-validations": "3.1.1",
    "ember-data": "^2.9.0",
    "ember-data-url-templates": "0.2.0",
    "ember-export-application-global": "^1.0.5",
    "ember-gestures": "0.4.2",
    "ember-hammertime": "1.1.2",
    "ember-load-initializers": "^0.5.1",
    "ember-moment": "6.1.0",
    "ember-one-way-controls": "1.1.1",
    "ember-pikaday": "1.0.0",
    "ember-resolver": "^2.0.3",
    "ember-route-action-helper": "2.0.0",
    "ember-simple-auth": "1.1.0",
    "ember-sortable": "1.9.0",
    "ember-welcome-page": "^1.0.3",
    "emberfire": "1.6.6",
    "emberx-select": "2.1.1",
    "loader.js": "^4.0.10",
    "rupture": "0.6.1"
  }

**Comment by jgwhite** [comment]
Could you post exactly the lines you’re using to import them in `tests/helpers/start-app.js` and also the error message you’re seeing?

**Comment by alexparker** [comment]
Apologies - I am not sure what the problem was, but something else must have been wrong, because it started working for me without changing the import line :shrug: :)
