### ISSUE TITLE
Add check for `isDestroying`?

### ISSUE THREAD

**Issue by jacobq** [jgwhite/ember-sortable#129]
In my application I have a list of sorted items shown on a page, each of which as a "delete button" that corresponds to an action that called `deleteRecord` on the associated model item. This seems to work most of the time, but there appears to be a race condition wherein I can start to drag an item just after clicking the delete button. In that case, `Ember` throws an error when `ember-sortable` tries to set a property on said item. Am I doing something wrong here? It seems that this could be easily addressed by either wrapping these lines in a try/catch or first checking to see if `this.get('isDestroying')` is `true`.

Stack trace
```
ember.debug.js:17634 Error: Assertion Failed: calling set on destroyed object: <my-app@component:sortable-item::ember2743>.isDropping = [object Boolean]
    at assert (ember.debug.js:5700)
    at Object.assert (ember.debug.js:17372)
    at Object.set (ember.debug.js:22036)
    at Class.set (ember.debug.js:34722)
    at Class._complete (sortable-item.js:675)
    at Object.join (ember.debug.js:770)
    at Function.run.join (ember.debug.js:22289)
    at ember.debug.js:22352
    at tryCatch (ember.debug.js:58528)
    at invokeCallback (ember.debug.js:58543)
```

Relevant lines from `sortable-item.js`
```
/**
  @method _complete
  @private
*/
_complete: function _complete() {
  (0, _emberInvokeAction.invokeAction)(this, 'onDragStop', this.get('model'));
  this.set('isDropping', false);
  this.set('wasDropped', true);
  this._tellGroup('commit');
}
```

**Comment by acburdine** [comment]
Hmm....this is definitely an interesting problem - I'll definitely look into this further 😄

**Comment by jacobq** [comment]
Thanks. For now I've moved my "drag handles" further away from the button so that it is at least harder to do.

**Comment by bschouwerwou** [comment]
I'm running into a similar error. I'm using a `computed` property which is used to build the sortable items that I loop over with `each`. It depends on an array from my model, which I update when an item is moved, resulting in the computed property to be recomputed and update the view.

When I drag an item I will usually get the error. In my case it's coming from the `_drag` function when setting `y`. Occasionally it will not throw the error.
```
Assertion Failed: calling set on destroyed object: <app@component:sortable-item::ember2447>.y = 226
```
