### ISSUE TITLE
Is possible to generate an 1.9.4 version ? with the new distance attribute ?

### ISSUE THREAD

**Issue by BnitoBzh** [jgwhite/ember-sortable#146]

**Comment by acburdine** [comment]
Yes, I'll get on it this weekend. Apologies for the delay!

**Comment by Syzygy24** [comment]
Ah, I was wondering why I couldn't get that working. Thanks!

**Comment by BnitoBzh** [comment]
@acburdine ?

**Comment by acburdine** [comment]
Working on it now!

**Comment by acburdine** [comment]
Ember-Sortable 1.9.4 published 😄 Again, sorry for the delay!
