### ISSUE TITLE
outdated demo (/gh-pages)

### ISSUE THREAD

**Issue by H1D** [jgwhite/ember-sortable#152]
Tried http://jgwhite.co.uk/ember-sortable/demo/ on mobile chrome and it scrolls page while dragging

**Comment by jgwhite** [comment]
Thanks for reporting. Could you provide the precise version of Chrome?

**Comment by H1D** [comment]
@jgwhite Chrome 60

I think I found out why. Seems like demo app is a bit outdated (build using old version). `handle` element has no `touch-action:none`:
![image](https://user-images.githubusercontent.com/697625/30298869-bb5fcdb4-9755-11e7-84ea-10a0c10494f9.png)

Same app [rebuild](https://ember-twiddle.com/7068cc6921dc42fa53a4cce410e79f73?fileTreeShown=false&numColumns=0) at ember-twiddle with latest ember-sortable has `touch-action:none`:
![image](https://user-images.githubusercontent.com/697625/30298904-e8cb4bac-9755-11e7-93a4-9ff36165824e.png)

**Comment by acburdine** [comment]
@H1D yeah that's not surprising 😕 I've had it on my radar for a while to update the demo - will get to it as soon as I am able.

**Comment by jgwhite** [comment]
Good sleuthing @H1D!

**Comment by jgwhite** [comment]
Have rebuilt the demo against 1.10.0
