### ISSUE TITLE
Replace `model.items` example with just `model`

### ISSUE THREAD

**Issue by zeppelin** [jgwhite/ember-sortable#19]
It seems to me that the only reason why `model.item` is used in the examples, is because `this.set('currentModel', anArray);` doesn't trigger a property change. But since Ember has a special syntax for dealing with arrays, I'd consider updating the examples to the following, if you feel it's not that confusing:

```js
actions: {
  reorderItems(newOrder) {
    this.set('currentModel.[]', newOrder);
  }
}
```

I can submit the PR if you're in favor.

**Comment by jgwhite** [comment]
You’re right. It was partly to get around the problem of `this.set('currentModel', newOrder)` being problematic and partly because `{{#each model.items as |item|}}` seemed a touch more obvious.

This trick is very cool:

```js
this.set('currentModel.[]', newOrder);
```

I had no idea you could do that!

My only concern is it might be a bit *too* magic and thus distracting. This version is equivalent but not as fun:

```js
this.get('currentModel').setObjects(newOrder);
```

I’d still be worried that users might think they have to use Ember-specific array operations to work with the component. I dunno, what do you think?

**Comment by zeppelin** [comment]
Wow, totally forgot about `setObjects`!

Actually, I only submitted an issue instead of a PR, because it's been quite a while since I was explaining Ember to a newcomer - therefore I have no idea what is considered to be confusing - and would wanted to rely on your opinion :D

That said, `setObjects` is IMO much better than `.[]`, because people can google it quickly and read the explanation in the API docs. Plus, they might learn to be more aware of dealing with arrays in Ember in general.

> I’d still be worried that users might think they have to use Ember-specific array operations to work with the component. I dunno, what do you think?

I would flip a coin :)

**Comment by jgwhite** [comment]
Haha. I really like the suggestion (and learned something cool from it) but I think let’s leave it as-is for now.

**Comment by zeppelin** [comment]
Sure thing, it was only a suggestion because for me it was confusing for the opposite reason: I couldn't figure out for the first glance if the data structure has to be as it is written in the example.

But you may certainly be right, and it's best if these intricacies of Ember is left to each person to explore.

**Comment by jgwhite** [comment]
Yeah, it’s tricky. The point I wanted to make was “you do whatever you like with the new array” but inevitably whatever we put in the example ends up looking prescriptive :confused: 

Maybe a really deliberate comment would be better…

**Comment by zeppelin** [comment]
Yeah, I was also thinking about adding a comment, but that would mean explaining how *Ember* itself works, and I felt that's out of scope.
