### ISSUE TITLE
Please, write normal readme with working examples.

### ISSUE THREAD

**Issue by OpakAlex** [jgwhite/ember-sortable#24]

**Comment by jgwhite** [comment]
Could you elaborate?

**Comment by jgwhite** [comment]
The [Usage](https://github.com/jgwhite/ember-sortable#usage) section of the readme provides example code that mirrors that driving the example page.

**Comment by OpakAlex** [comment]
yes, but you need show more about items :) Because i see in code `items`, so put message this is your sorted collection :)

**Comment by jgwhite** [comment]
Do you mean more explanation of where `model.items` comes from?

**Comment by OpakAlex** [comment]
yes.

**Comment by jgwhite** [comment]
Good idea. Thanks!

**Comment by OpakAlex** [comment]
thank you!
