### ISSUE TITLE
How about horizontally sort?

### ISSUE THREAD

**Issue by OpakAlex** [jgwhite/ember-sortable#25]

**Comment by jgwhite** [comment]
Yup, absolutely. Probably in 1.1.0.

**Comment by OpakAlex** [comment]
@jgwhite maybe you need help?

**Comment by jgwhite** [comment]
@OpakAlex absolutely. Pull requests most certainly welcome :)

**Comment by jgwhite** [comment]
I have an opened an issue to track this feature: #26

**Comment by OpakAlex** [comment]
:) ok, i will see.
