### ISSUE TITLE
Smart scrolling

### ISSUE THREAD

**Issue by rsaccon** [jgwhite/ember-sortable#33]
long lists, which are not all visible, cannot be sorted with ember-sortable. Do you plan to addapt a smart scrolling approach like done in https://github.com/RubaXa/Sortable ?

demo:

http://jsbin.com/kohamakiwi/1/edit?html,js,output

**Comment by jgwhite** [comment]
Thanks for raising this. It’s something ember-sortable definitely needs. PRs welcome, as always :smile:

**Comment by zeppelin** [comment]
+1 for this, might dig in if my (rather tight) schedule allows to do so.

**Comment by jgwhite** [comment]
@zeppelin awesome, please do. My schedule is also proving hard to navigate at the moment.

**Comment by jgwhite** [comment]
Part of the groundwork for this is being laid in #39

**Comment by Glavin001** [comment]
I also want this feature. Anything I can do to contribute? I may need some initial guidance as to where to look and some pointers as to what the code should be doing.

When I have a chance, I am going to look through the ember-sortable code and learn more about how it works, and then take a look at  https://github.com/RubaXa/Sortable and see how they got it working.

Any advise would be greatly appreciated. Thanks!

**Comment by jgwhite** [comment]
@Glavin001 we would love a PR to implement this behaviour. You’ll probably want to add the logic to `addon/mixins/sortable-item` and have it kick into life when dragging begins. I think the trickiest part will be identifying _which_ element ought be scrolled.

**Comment by ianbale** [comment]
My fork is now considerably different to this original, but I just made the auto-scroll work by making a single change. Hopefully it'll work for you too...

In mixins/sortable-item/js, find _primeDrag and comment out event.preventDefault();

Leave event.stopPropagation(); in there though, otherwise as you drag it selects all the text that you drag over...

**Comment by jgwhite** [comment]
Hey, sorry for the slow response. New year has been busy so far. Any chance you could formulate some of these awesome changes into a pull request?

**Comment by ianbale** [comment]
Will do at some point... But I have a few bugs to iron out first. Plus, it really needs a tidy up now. I've kinda rushed things so that I can have something working for my project. It's a bit messy under the hood now...

**Comment by osxi** [comment]
I have a component that basically contains a table and did something like this a few minutes ago using this as my `onDragStart` handler: 

```
seriesDragStartHandler(series) {
      if (Ember.isPresent(this.get('draggingSeries'))) {
        this.$('table').on('mouseover', e => {
          Ember.run.debounce(() => {
            let $table = this.$('table');
            let mouseX = e.clientX;
            let scrollLeft = $table.scrollLeft();
            let rightOffset = ($(window).width() - ($table.offset().left + $table.outerWidth()));
            let leftOffset = $table.offset().left;
            let margin = 100;

            if (mouseX > ($(window).width() - rightOffset - margin)) {
              console.log('scroll right');
              $table.animate({scrollLeft: $table.scrollLeft() + 50}, 25);
            }

            if (mouseX < (leftOffset + margin)) {
              console.log('scroll left');
              $table.animate({scrollLeft: $table.scrollLeft() - 50}, 25);
            }
          }, 100);
        });
      }
    },
```

**Comment by osxi** [comment]
I have a component that basically contains a table and have managed to implement this using the following as my `onDragStart` handler:

```
dragStartHandler() {
  this.$('table').on('mouseover', e => {
    Ember.run.debounce(() => {
      let $table = this.$('table');
      let mouseX = e.clientX;
      let scrollLeft = $table.scrollLeft();
      let rightOffset = ($(window).width() - ($table.offset().left + $table.outerWidth()));
      let leftOffset = $table.offset().left;
      let margin = 100;

      if (mouseX > ($(window).width() - rightOffset - margin)) {
        console.log('scroll right');
        $table.animate({scrollLeft: $table.scrollLeft() + 50}, 25);
      }

      if (mouseX < (leftOffset + margin)) {
        console.log('scroll left');
        $table.animate({scrollLeft: $table.scrollLeft() - 50}, 25);
      }
    }, 100);
  });
},
```

The `onDragStop` handler is simply:
```
dragStopHandler() {
  this.$('table').off('mouseover');
},
```

I wouldn't say it's very smart but it does the job.

**Comment by jgwhite** [comment]
@osxi thanks for this. I’m tempted to recommend that consumers of ember-sortable roll their own smart-scroll or compose with a smart-scroll component. What do you reckon?

**Comment by osxi** [comment]
@jgwhite yeah I think that's advisable since it's implementation specific and there's other things involved like CSS (in my case, the table has `overflow-x: auto; display: block;`).

**Comment by jgwhite** [comment]
@osxi I’ll try to carve out time to add some guidance to the README based on your example.

**Comment by meliborn** [comment]
Any changes?

**Comment by jgwhite** [comment]
@meliborn the more I look at this, the more I think smart scrolling should not be built into ember-sortable. Instead, ember-sortable should be easily composable with other smart-scrolling solutions. [@osxi’s solution](https://github.com/jgwhite/ember-sortable/issues/33#issuecomment-174010730) is the approach I’d take in lieu of a dedicated library or component.

**Comment by tim-evans** [comment]
This has been completed with #104 🎉

**Comment by acburdine** [comment]
thanks @tim-evans!
