### ISSUE TITLE
Hooks should call _super

### ISSUE THREAD

**Issue by rlivsey** [jgwhite/ember-sortable#41]
Just ran into an issue where my own code didn't call `_super` on `didInsertElement` which stopped ember-sortable working, but the opposite could also happen (depending on mixin inclusion order).

`didInsertElement` etc should call `this._super()` once they've done their thing so we can pass the baton along.

**Comment by denzo** [comment]
Could this be fixed with using 'didInsertElement' event as oppose to overriding didInsertElement method.

Instead of doing this

```
didInsertElement: function() {
  // do your stuff here
  this._super();
}
```

Do this

```
myLogic: function() {
  // my logic goes here...
 // no need to call _super
}.on('didInsertElement')
```

**Comment by jgwhite** [comment]
Very good points. Stef has advocated overriding `didInsertElement` in addons over using the hook. I think we’ll go with that approach. I don’t remember the specifics of the argument but can probably find a link to the conversation if anyone’s interested.
