### ISSUE TITLE
Table rows move incorrectly when sorting

### ISSUE THREAD

**Issue by ForSpareParts** [jgwhite/ember-sortable#43]
When a `sortable-group` contains `<tr>` elements as its `sortable-item`s, dragging an item to sort results in the rest of the table rows being pushed much further down the height of the table than is expected. The magnitude of the effect seems to derive from the position of the table on the page -- in a real page, where the table was further down, the rows were pushed so far out that they were not visible.

**Comment by ForSpareParts** [comment]
Repro: https://github.com/ForSpareParts/ember-sortable-43-repro

**Comment by jgwhite** [comment]
Thanks for reporting. I’ll look into this as soon as I can. If you find the source of the bug, PRs are very much appreciated :smile:

**Comment by jgwhite** [comment]
Okay, couple thoughts so far:

1. `sortable-group$_getFirstItemPosition` needs work. Seems like it could be as simple as:

   ```js
   _getFirstItemPosition() {
      let direction = this.get('direction');
      return this.get(`items.firstObject.${direction}`);
   }
   ```

   I forget the exact history of this method. There must have been a rationale for using a stooge.

2. The above gets us part way there but we still need to find a way to account for `border-collapse: separate` and `cell-spacing` in `sortable-item$width` and `sortable-item$height`.

**Comment by jgwhite** [comment]
#45 begins to address this problem.

**Comment by jgwhite** [comment]
@ForSpareParts [1.4.0](https://github.com/jgwhite/ember-sortable/releases/tag/v1.4.0) is out. This should improve table sorting. There may still be work to do. Let me know how you get on.
