### ISSUE TITLE
onChange fires onClick

### ISSUE THREAD

**Issue by mehulkar** [jgwhite/ember-sortable#50]
it looks like when i click an element, it also fires the onChange action. i'm guessing this also reinserts the element? i'm yielding a component templet inside the sortable items and they lose their state onChange. So they're also losing their state

**Comment by jgwhite** [comment]
This can be counteracted today by declaring a `handle`.

I’d be open to a PR that suppress `onChange` unless the order actually changes. It’ll add complexity but sounds valuable.

**Comment by mehulkar** [comment]
I have a `handle` defined, just FYI. 

I'll think about how to do implement, but honestly, more likely I'll end up changing my design to _not_ have an "expand" button in each element that needs to be maintained. Super spike project and this library got me 80% of the way, so I'm satisfied for now. (Feel free to close this, if you don't think the additional complexity is a huge win)

**Comment by jgwhite** [comment]
@mehulkar I’ll keep this open. I think it’s something we probably *should* account for.

**Comment by opsb** [comment]
@jgwhite Vice versa when you drag an item the click event fires... there doesn't appear to be an easy way to tease the two apart. jquery-ui-sortable takes the approach of only initiating a drag if the mouse is moved after the mousedown. It prevents the click after a successful drag by adding a listener to catch the next click.

**Comment by jgwhite** [comment]
Closed by #51
