### ISSUE TITLE
Can't sort items of different sizes

### ISSUE THREAD

**Issue by opsb** [jgwhite/ember-sortable#52]
The maths for the positioning currently assumes that the items all have the same dimensions. I haven't dug into the positioning code yet but I suspect this is going to be tricky...

**Comment by opsb** [comment]
Hmm, I see the height is calculated based on the element, I'll have to dig in and see what's throwing the positioning off in my app.

**Comment by jgwhite** [comment]
Thanks for reporting. It's possible there are combinations of styles we haven't properly accounted for yet. Let us know what you find out.

**Comment by jgwhite** [comment]
@opsb any luck identifying the problem here?

**Comment by opsb** [comment]
@jgwhite other things have taken priority unfortunately, will get back to this at some point though.

**Comment by jgwhite** [comment]
@opsb I’m going to close this for now but feel free to re-open if appropriate.

**Comment by opsb** [comment]
@jgwhite thanks, I've taken care of this in the work I'm doing for the multiple lists issue.
