### ISSUE TITLE
emit mouseDown event

### ISSUE THREAD

**Issue by mehulkar** [jgwhite/ember-sortable#54]
In a long-ish list, when re-ordering, I want to zoom out the UI (apply a CSS transform to shrink all the elements).
This will allow the user to easily drag and drop elements a large number of elements away.
I think I could do this if we had a mouseDown event and i could do custom stuff from it. 

What do you think? I think it would mean exposing another handle like `onChange`.

**Comment by jgwhite** [comment]
Seems reasonable to me. The UI you describe sounds cool. I wonder if the hook you’re after is something like `prepare` or `before-sort` or `will-sort` — something that can return a promise so can defer sorting until animation is complete.

**Comment by mehulkar** [comment]
hmm. maybe I'm just unfamiliar with how the code is written, but I would have assumed that the "sorting" part is triggered when the element is dropped, no? In my head, I'm seeing it like this:

1. mouseDown
1. custom hook
1. dragEvent
1. dropEvent
1. onChange
1. custom hook

Soemthing like `will-sort` seems like it would fit in after `dropEvent` or after `onChange`. 
I'm looking for something after `mouseDown` and also after `dropEvent` to reverse whatever I did on mouseDown. 

Does that make sense?

**Comment by jgwhite** [comment]
I think you’re right that `will-sort` implies completing the sort.

Could you sketch out how you’d use this if it were implemented as `mouseDown`?

**Comment by jgwhite** [comment]
Mainly I’m curious as to what component will receive the action in this particular example.

**Comment by mehulkar** [comment]
I just looked through the code a little bit and it looks like the `onChange` event is fired in sortable-group in the `commit` function. I think `mouseDown` could be fired in the `prepare` function? A quick spike validated that I was able to send the action pretty easily!

**Comment by jgwhite** [comment]
@mehulkar I would still like to explore to possibility of giving this action a more specific name. Three reasons:

1. It could be a `touchstart` that triggers it
2. We’re cancelling the real `mousedown` with `preventDefault`
3. This may open the door to exposing many other DOM events as actions

It might not be a problem to overload `mousedown` with our synthetic version but I’d like to explore other possibilities.

This hook definitely has value but let’s make sure we nail it.

**Comment by mehulkar** [comment]
One thing that's tripping me up looking at the code is that I don't
understand what the sortable groups are for. Could you talk about a use
case for that?

On Monday, August 31, 2015, Jamie White <notifications@github.com> wrote:

> @mehulkar <https://github.com/mehulkar> I would still like to explore to
> possibility of giving this action a more specific name. Three reasons:
>
>    1. It could be a touchstart that triggers it
>    2. We’re cancelling the real mousedown with preventDefault
>    3. This may open the door to exposing many other DOM events as actions
>
> It might not be a problem to overload mousedown with our synthetic
> version but I’d like to explore other possibilities.
>
> This hook definitely has value but let’s make sure we nail it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgwhite/ember-sortable/issues/54#issuecomment-136577333>
> .
>


-- 

------
Mehul Kar
@mehulkar

**Comment by jgwhite** [comment]
`sortable-group` has n jobs:

1. Listen out for updates from the item being dragged
2. Put other items in position when dragging occurs
3. Collect up models from items to send in the `commit` action

Items should are not aware of each other — they are self-absorbed by design. `sortable-group` facilitates this.

**Comment by mehulkar** [comment]
what's the purpose of binding a model to the `sortable-group`? From the README, the only value of binding a model to the `sortable-group` is that this "group model" is included in the arguments passed to the `onChange` action, _in addition_ to the itemModels array. 

Aren't the `itemModels` going to be the same as the `groupModel` in a typical scenario?

**Comment by jgwhite** [comment]
@mehulkar the group model was added in #28. Typically it is the array you’re sorting, while the item models are the things in the array.

**Comment by jgwhite** [comment]
Here’s a fleshed out example:

```js
// app/routes/my-route.js
import Ember from 'ember';
const { Route, A } = Ember;

export default Route.extend({
  model() {
    return {
      collections: [
        A(['red', 'green', 'blue']),
        A(['big', 'medium', 'small']),
        A(['universe', 'galaxy', 'solar system'])
      ]
     };
  },

  actions: {
    // We’re using the same action handler for a bunch of different
    // collections so we need to know which collection we’re updating.
    updateCollection(collection, newOrder) {
      collection.setObjects(newOrder);
    }
  }
});
```

```hbs
{{! app/templates/my-route.hbs }}

{{#each model.collections as |collection|}}
  {{! Here we’re saying “when you fire the `onChange` action,
      send this particular collection along as the first argument” }}
  {{#sortable-group tagName="ul" model=collection onChange="updateCollection" as |group|}}
    {{#each collection as |item|}}
      {{#sortable-item tagName="li" model=item}}
        {{item}}
      {{/sortable-item}}
    {{/each}}
  {{/sortable-group}}
{{/each}}
```
