### ISSUE TITLE
Allow form fields within sortable

### ISSUE THREAD

**Issue by jgadbois** [jgwhite/ember-sortable#62]
I have a sortable with form fields.  If I don't specify a handle, the component doesn't allow me to focus into any of the form fields.

**Comment by jgwhite** [comment]
Hey sorry for the slow response — I’ve been on holiday :)

The tricky thing with this is that there are many elements which should short-circuit the sortable behaviour and it’s tricky to nail down a general rule without introducing complexity.

In these cases I tend to add a handle that is absolutely positioned, width 100% height 100%, and behind all other elements.

**Comment by jgadbois** [comment]
Ok that should work, thanks.
