### ISSUE TITLE
Disable on right click

### ISSUE THREAD

**Issue by jgadbois** [jgwhite/ember-sortable#63]
Right click currently starts drag.  I'm constantly hitting it when I try to inspect element in Chrome.

**Comment by jgwhite** [comment]
:+1:

I’m

**Comment by jgwhite** [comment]
Sorry — clicked the wrong button!

Agreed this should be built-in.

**Comment by jgwhite** [comment]
1.6.2 is published with the fix. Thanks for the issue!
