### ISSUE TITLE
Uncaught TypeError: Cannot read property 'css' of undefined

### ISSUE THREAD

**Issue by woodland021** [jgwhite/ember-sortable#70]
Hey guys,

I just implemented ember sortable successfully but when I go about and drag an item ontop of the next item and drop it I get this in my console: Uncaught TypeError: Cannot read property 'css' of undefined

And then it immediately takes me to my homepage of my app..

Is this a bug? Or am I implementing it wrong?

Thanks,

Ethan

**Comment by jgwhite** [comment]
Hi Ethan

Thanks for using the addon :)

Could you post some of the template and component code? It sounds like it may be a documentation issue.

**Comment by woodland021** [comment]
jgwhite,

Thanks for the response :)

Here's my template file: https://gist.github.com/woodland021/d2163335a7fd4e8255e9
 
Here's my route file: https://gist.github.com/woodland021/93af832f2546fc2a1ef9

Also a friend called knownasilya tried to help me out by making his own build with my code and he said it works fine: https://github.com/knownasilya/sortable-test

Check those out and see if you can go about seeing the issue i'm very excited to get this working..thanks for your help again!

Ethan

**Comment by jgwhite** [comment]
Hmm, I don't see a `reorderItems` action in your route. Is it defined elsewhere?

**Comment by woodland021** [comment]
jg,

Do you think that would be my problem? I haven't created it yet.

**Comment by jgwhite** [comment]
Could you post the revised route? You'll definitely need a functioning action handler.

**Comment by woodland021** [comment]
import Ember from 'ember';

export default Ember.Route.extend({
  renderTemplate: function() {
    this.render();
    this.render('writings.Footerjs', { into: 'envisionboards.envisionboard', outlet: 'footer_js' });
  },
  model: function(params) {
    return Ember.RSVP.hash({ //need to change this later to one return of one model
      ebdatum: this.store.query('ebdatum', {eb_id: params.id}),
      envisionboard: this.store.find('envisionboard', params.id)
    });
  },
  actions: {
    reorderItems(groupModel, itemModels, draggedModel) {
      groupModel.set('ebdatum', itemModels);
    },
  }
  // afterModel: function(model) {
  //   // console.log(model.get('firstObject.eb_id'));
  // }
});


That's my route right now.

**Comment by jgwhite** [comment]
Could you try:

```js
reorderItems(groupModel, itemModels) {
  groupModel.setObjects(itemModels);
}
```

**Comment by woodland021** [comment]
jg, 

Still the same error... :/

Uncaught TypeError: Cannot read property 'css' of undefined

This error prints twice too.

These are the lines of code the error leads me to:

First Error: this.$().css({
          transform: 'translateY(' + dy + 'px)'
        });

Second Error: var property = el.css('transition-property');

Both say cannot read property 'css' of undefined..

I assume it has to do something with my jQuery? Not sure...

Thanks again jg!

Ethan

**Comment by jgwhite** [comment]
Would it be possible to get access to the codebase? I'd like to fire up the debugger and see exactly what's going on.

**Comment by woodland021** [comment]
jg,

Would you be down with a screenshare? I can't really give you access to this repo due to NDA reasons.

**Comment by woodland021** [comment]
jg,

got it working! :)

**Comment by jgwhite** [comment]
Oh awesome :D How did you fix it?

For the record: I am always down for a screenshare, timezones permitting.

**Comment by woodland021** [comment]
jg,

I went about and fixed it by actually doing a git reset on my repo haha.

Had no idea what the problem was. But works swimmingly now! Thanks!
