### ISSUE TITLE
Limit drag area

### ISSUE THREAD

**Issue by lolmaus** [jgwhite/ember-sortable#72]
Thank you for the awesome addon!

It should be possible to prevent draggable items to be moved outside the specified area (typically the `sortable-group`).

**Comment by jgwhite** [comment]
@lolmaus sounds reasonable. Do you mean that the element being dragged would refuse to move outside its bounding rectangle?

**Comment by lolmaus** [comment]
Yes.

**Comment by superlou** [comment]
This would help me out, too.

**Comment by davelowensohn** [comment]
+1

Definitely an edge case, but I'm using this inside of an `{{ember-modal-dialog}}` and dragging a sortable outside of the modal's boundaries causes the whole app to break.

**Comment by scottmessinger** [comment]
Closing since it's fixed in #100

**Comment by scottmessinger** [comment]
Actually, this might not be fully fixed in #100. @lolmaus Does that commit take care of it? If not, let's reopen.

**Comment by lolmaus** [comment]
I'm not currently using `ember-sortable`.

Let's assume #100 fixes it until proved otherwise.

@davelowensohn :bowing_man:

**Comment by matthewdias** [comment]
Hmm I don't think this is fixed. Still seeing this issue.
