### ISSUE TITLE
Passing actions up from the items

### ISSUE THREAD

**Issue by jgadbois** [jgwhite/ember-sortable#73]
Each of my sortable items is a component and has actions I need to bubble up to the top-level controller (ie the controller for the template rendering the sortable group)

Is there a way to do this?

**Comment by jgwhite** [comment]
There are a few different approaches. Could you post some example template code?

**Comment by jgadbois** [comment]
```
        {{#sortable-group tagName="ul" model=sortedExercises class=exerciseListClasses onChange="reorderItems" as |group|}}
          {{#each sortedExercises as |ex| }}
            {{#sortable-item tagName="li" class='exercise' handle='.creator-exercise-header' model=ex group=group onDragStart='dragStarted' onDragStop='dragStopped'}}
              {{workout-plan/workout-exercise ex=ex useMetric=plan.useMetric edit='edit'}}
            {{/sortable-item}}
          {{else}}
            No exercises have been added yet.
          {{/each}}
        {{/sortable-group}}
```

The part in question is the `edit='edit'` in the inner portion.

I tried wrapping the whole thing in a `with this as |controller|` and making the action `'controller.edit'` but that didn't seem to work.

**Comment by jgwhite** [comment]
As far as I can tell this should work as expected. The scope shouldn't change within any of these component blocks.

Which part of `workout-plan/workout-exercise` triggers the `edit` action?

**Comment by jgadbois** [comment]
The `sendAction` inside the `workout-exercise` component gets triggered, but then it says nothing is handling the second `edit` (so component action does get triggered, but then controller action is not handled)

**Comment by jgwhite** [comment]
Will investigate. Can I ask which version of Ember you’re running?

**Comment by jgadbois** [comment]
```
DEBUG: -------------------------------ember.debug.js:5379 
DEBUG: Ember      : 1.13.7ember.debug.js:5379 
DEBUG: Ember Data : 1.13.9ember.debug.js:5379 
DEBUG: jQuery     : 1.11.3ember.debug.js:5379 
DEBUG: -------------------------------
```

**Comment by jgwhite** [comment]
Thanks. I’ll see if I can put together a minimal reproduction.

**Comment by jgadbois** [comment]
Thanks!

**Comment by jgadbois** [comment]
This is actually seems to be working fine without the `#with`.  I think my dev just made a syntax error or something, sorry about that.

**Comment by jgwhite** [comment]
No need to apologise. No bug report is wasted!
