### ISSUE TITLE
Drag and drop within a grid.

### ISSUE THREAD

**Issue by shidel-dev** [jgwhite/ember-sortable#75]
Thank you for an awesome addon!

I would like to use ember-sortable in the context of a grid layout. Along the lines of this: https://greensock.com/?example=sortable-grid-using-draggable. 

What are your thoughts on adding support for this sort of layout?

**Comment by jgwhite** [comment]
Yes, we’d love for ember-sortable to support this sort of behaviour out of the box. However, in the greensock example there is a lot of extra grid-arrangement code at work. The question is: how can ember-sortable best interoperate with this type of arrangement logic?

**Comment by steffenbrem** [comment]
@jgwhite I think you just need to handle both the `x` and `y` axis. I haven't looked too much in the code yet, but I think it would be easy to implement for someone who knows this addon well. From what I know you check multiple times in your code for which dimension (axis) your working in and apply changes based on that axis. I might be wrong, but it may almost already be implemented.

**Comment by jgwhite** [comment]
@steffenbrem you're absolutely right that we'd need to track both axes simultaneously. There still remains the question of how to rearrange the other items when a drag is in process. Or rather, how to provide an API for custom "reflow" procedures.

In the case of a grid like the one mentioned, ember-sortable wouldn't be able to do much for you automatically. The reflow logic would need to be provided via a hook, and report back the new order somehow. This gets a little tricky with actions which, before the arrival of closure-actions, could not provide a return value.

I'd welcome proposals for what the API should look like for overriding the "arrange" procedure.

**Comment by BryanCrotaz** [comment]
I'm working on this for a client - I'll try and work out a PR

**Comment by meliborn** [comment]
Any news? Doesn't work with multiple columns as well.

**Comment by jgwhite** [comment]
I’m going to close this for now as it’s beyond the scope of ember-sortable as it stands today. If anyone makes progress, feel free to re-open and/or submit a PR.
