### ISSUE TITLE
Augmenting `transform`

### ISSUE THREAD

**Issue by samselikoff** [jgwhite/ember-sortable#79]
(Great lib!)

Is there a way to augment the `transform` property on the dragging element? 

I was hoping to achieve [this effect](http://chenglou.me/react-motion/demos/demo8-draggable-list/) by using `transform: scale` on the dragging element, but the transforms added by this lib override it. As far as I know there's no way to stack transforms in CSS.

If not, perhaps I could think through an API and PR it. Or maybe the library could check if there's a `transform` property, and just replace the `translateY` piece of it. Thoughts?

**Comment by jgwhite** [comment]
Sorry for the slow reply — was out of the country last week.

I’d be very open to a API proposal/PR for this :D

**Comment by raelbr** [comment]
This effect could me managed by including a transition and transform: scale() in a child element... for example:

```
{{#sortable-item tagName="li" classNames="sortable-item"}} 
   <a class="tab-style">  content  </a>
{{#sortable-item}}
```

In this case, you wont set any css style to the "sortable-item" class, but let all style be applied in the "tab-style" class.

The transform used to sort the elements will be applied in the "sortable-li", and then... just do the magic:

```
.sortable-item a.tab-style{
  transition: all 0.3s
} 
.sortable-item.is-dragging a.tab-style{
  transform: scale(1.5)
} 
```
Good luck! =)

**Comment by jgwhite** [comment]
@raelbr nice! Thanks :D

**Comment by samselikoff** [comment]
I like this - I'll reopen if I have any problems once I get a chance to try it out :)
