### ISSUE TITLE
Saving Order

### ISSUE THREAD

**Issue by srsgores** [jgwhite/ember-sortable#80]
What is the recommended approach for saving order to `groupModel` in ember data?  How can we persist order to `groupModel` such that the order can be retrieved and displayed in the view as it was arranged?

My current implementation:

`deck.hbs`:

```
{{#sortable-group tagName="ul" model=model class="deck-slides-nav-slides" onChange="reorderItems" as |group|}}
            {{#each model.slides as |slide|}}
                {{#sortable-item tagName="li" model=slide group=group handle=".handle" class="deck-slides-nav-slides-slide"}}
                    <span class="handle">&varr;</span>
                    {{#link-to "admin.decks.deck.slides.slide" slide class="deck-slides-nav-slides-slide-link"}}
                        {{#slide-instance slide=slide deck=model onRemove="removeSlide"}}{{/slide-instance}}
                    {{/link-to}}
                {{/sortable-item}}
            {{/each}}
{{/sortable-group}}
```

`routes/deck.js`:

```
export default Ember.Route.extend({
    model(params) {
        return this.store.findRecord("deck", params.deck_id);
    },
    actions: {
        reorderItems(groupModel, itemModels, draggedModel) {
            debugger;
            groupModel.set("slides", itemModels);
            return Ember.RSVP.all([draggedModel.save(), groupModel.save()]);
        }
    }
});
```

In this case, I am suspecting that order is saved from within the structure of the payload json request sent with `save()`, but in cases where the server returns items in its own sorted order, what is the recommended approach to persisting order?

**Comment by jgwhite** [comment]
This sounds more like an ember-data question than strictly a sortable one but it is a good question nonetheless.

In this case, are `slides` embedded onto the `deck` model?

Could you post an example of the JSON payload?

**Comment by raelbr** [comment]
It depends on what your backend is expecting... In i project i'm working on, the backend receives a PATCH with the new position of the rearranged element (tab in this case), and them, all the elements of this group will receive an updated position, and it's all done in the backend. This works fine for us because we work with an auto-save approach...

But if it's not your case and you have a Save Button for the rearranged elements, maybe you can go with a custom payload with an array associating the element's ids with the position, and the backend deal with the rest.

**Comment by mcfiredrill** [comment]
I'm taking a similar appraoch to @raelbr , in my case I'm using rails and the library ranked_model:
https://github.com/mixonic/ranked-model

I just set the new position attribute before I save the dragged model.
```
draggedModel.set('position_position', draggedToIndex);
```

**Comment by jgwhite** [comment]
Thanks for all the useful feedback. Closing this to keep the issues list tidy.
