### ISSUE TITLE
Manually refresh model, and other options

### ISSUE THREAD

**Issue by raelbr** [jgwhite/ember-sortable#84]
Hey there. First of all, what a nice addon! I like the look and feel of the animated objects when sorting...

But i'm currently facing some issues while trying to save the elements position in the server... I need to send only the data from the item that had it's position changed, and i can't replace the model with a new Array, cause i have some dynamic itens that can be added and removed, and i would lost the bind doing this.

So... I would like to know if is there some option to turn off the auto-refresh model, so then i can refresh it only after the servers response. Is that possible?

(sorry, i cant post any code snippet doe to the company's contract)

Other thing that would be nice, is to add a "newPosition" argument in the actions "onDragStop" and "onChange"... Because, in my case, i need to set the new position index in a property "position" and PATCH it to the server... I managed to make it by doing a forEach in the groupModel, look for the item.id and get the index of the match, but would be very helpfull to have some argument with this value...

Thank you very much!

**Comment by jgwhite** [comment]
Hi @raelbr 

Thank you for your kind words.

Could you clarify some details for me:

1. Are you using Ember Data?
2. When you say you would “lose the bind” — what kind of binding are we talking about?
3. I don’t fully understand what you mean when you say “auto-refresh model”. Could you try re-phrasing?

Here’s what I’d expect a solution to look like:

```hbs
{{#sortable-group onChange="reorder" as |group|}}
  {{#each sortedItems as |item|}}
    ...
  {{/each}}
{{/sortable-group}}
```

```js
sortedItems: computed('items.@each.position', function() {
  return this.get('items').sortBy('position');
}),

reorder(orderedItems, draggedItem) {
  let position = orderedItems.indexOf(draggedItem);
  draggedItem.set('position', position);
  draggedItem.save();
}
```

Let me know if I’ve misinterpreted your explanation.

Thanks for using ember-sortable, and for your feedback :)

**Comment by raelbr** [comment]
Hey there. Thank you for the answere... And sorry for taking too long to reply... Actually all the problems i had was because i forgot to provide the model to the sortable-group! So i made like the tutorial and everything is fine now!
Thank you very much!
