### ISSUE TITLE
[bug] element dragging forever

### ISSUE THREAD

**Issue by raelbr** [jgwhite/ember-sortable#86]
Hello there!

I use the ember-sortable to sort some bootstrap tabs, but i'm having a little bug...

I don't know exactly what triggers this bug since it occurs only some times... but what happens is that i click in a tab and it starts the drag forever, and i'm unable to cancel the drag or click in any element in the current page.

Since we have the "onDragStart" action, maybe i can set a simple click event to cancel the drag. But for this, i just need to know if is there some event, or some other way to cancel the drag.

Thank you very much!

Rael

**Comment by jgwhite** [comment]
Hi @raelbr 

Thanks for filing an issue. Could you provide code samples so I can get more of a sense of what’s happening, particularly in the `onDragStart` action handler.

**Comment by raelbr** [comment]
{{#sortable-group
  tagName="ul"
  direction="x"
  classNames="nav nav-tabs"
  model=model
  onChange="reorderTabs" as |group|
}}

  {{#each model.tabs as |tab|}}

    {{#sortable-item
      tagName="div"
      model=tab
      group=group
      onDragStart="tabDrag"
      onDragStop="tabDrop"
    }}
      <li>
        {{#link-to 'routename' tab.id}}
          {{tab.name}}
        {{/link-to}}
      </li>

    {{/sortable-item}}

  {{/each}}

{{/sortable-group}}

tabDrag and tabDrop actions have nothing set yet... Maybe the link-to is causing the issue? Just a quick note that it's not always that this bug occur... i really don't know what is causing this bug, if its the way we click or drag the tab, if is while a transition... Couldn't get a cause for this bug yet... Only thing i know is that sometime it happens =(

Sorry about the lack of information... But, if is there someway to force cancel the drag, i think i can solve this problem... is there some action, event, or some other way to turn down the dragging?

Thank you very much!

**Comment by jgwhite** [comment]
> is there some action, event, or some other way to turn down the dragging

Not yet, but it would be a good thing to add.

We do have some built-in knowledge of when an interaction is not a drag — i.e. when there is very little movement between mousedown and mouseup — but perhaps it is not covering your case.

In the meantime, I would recommend adding a separate element to act as drag handle.

**Comment by raelbr** [comment]
Thank you for your reply @jgwhite .

If i get a solution for this i share here. And if i manage to make an "cancel-drag" event that works fine in the plugin, i send a PR ;)

**Comment by raelbr** [comment]
Hey there... I think i fixed this bug.
I managed to resolve this issue by adding the click event in the cancelStartDragListener inside the _primeDrag method, and also in the _startDrag.

```
  /**
    @method _primeDrag
    @private
  */
  _primeDrag(event) {
    let handle = this.get('handle');

    if (handle && !$(event.target).closest(handle).length) {
      return;
    }

    event.preventDefault();
    event.stopPropagation();

    let startDragListener = event => this._startDrag(event);

    function cancelStartDragListener() {
      $(window).off('mousemove touchmove', startDragListener);
    }

    $(window).one('mousemove touchmove', startDragListener);
    $(window).one('click mouseup touchend', cancelStartDragListener);
  },

  /**
    @method _startDrag
    @private
  */
  _startDrag(event) {

    if (this.get('isBusy')) { return; }

    let drag = this._makeDragHandler(event);

    let drop = () => {
      $(window)
        .off('mousemove touchmove', drag)
        .off('click mouseup touchend', drop);

      this._drop();
    };

    $(window)
      .on('mousemove touchmove', drag)
      .on('click mouseup touchend', drop);

    this._tellGroup('prepare');
    this.set('isDragging', true);
    this.sendAction('onDragStart', this.get('model'));
  },
```
Can this change impact someway in the plugins functionality?

**Comment by jgwhite** [comment]
@raelbr seems good. Could you submit a pull request with this change. Let’s see what the test suite says :)

**Comment by raelbr** [comment]
Well, i got a FAIL in Travis CI. Is there something i did wrong?

**Comment by NullVoxPopuli** [comment]
any updates? I think I have a similar issue, where link-to is causing a full page navigation after mouse-up
