### ISSUE TITLE
Events not firing

### ISSUE THREAD

**Issue by IAmJulianAcosta** [jgwhite/ember-sortable#96]
I have the following markup:
```
{{#sortable-group tagName="ul" onChange="reorderItems" as |group|}}
	{{#each items as |item|}}
		{{#sortable-item tagName="li" model=item group=group handle=".handle" onDragStart="dragStarted" onDragStop="dragStopped" }}
			<span class="handle">&varr;</span>
			{{item.name}}
		{{/sortable-item}}
	{{/each}}
{{/sortable-group}}
```

The action `dragStarted` fires, but `dragStopped` and `reorderItems` don't, and each element never loses `is-dropping` class after dropping.

Version: v1.8.1

**Comment by jgwhite** [comment]
Can I ask what logic is being performed in the `dragStarted`, `dragStopped`, and `reorderItems`?

Also, can I ask what browser/OS you’re observing this behaviour on?

**Comment by IAmJulianAcosta** [comment]
Hi, the logic is a simple `console.log` to test if it works, but only prints in `dragStarted`. 

Mac OS, tested in latest chrome and safari, `"ember": "2.6.0"`. I created a route only for trying this and avoiding conflicts, but the problem continues.

![screen shot 2016-06-20 at 10 02 23 a m](https://cloud.githubusercontent.com/assets/1844640/16199174/2d23e820-36ce-11e6-92b0-5488631bac4f.png)

I'm not 100% sure, but checking the source, it seems that is related with `_waitForTransition()` not firing.

**Comment by IAmJulianAcosta** [comment]
Added several breakpoints in the following code:

```
return new Promise(resolve => {
      run.next(() => {
        let duration = 0;

        if (this.get('isAnimated')) {
          duration = this.get('transitionDuration');
        }

        run.later(this, resolve, duration);
      });
    });
```

And never executes

**Comment by jgwhite** [comment]
Seems like we have an oversight in the `isAnimated` detection logic. Could you post your CSS?

**Comment by IAmJulianAcosta** [comment]
I don't have any CSS for this part of the project, I just installed the addon and tried it, but, here is the [CSS](http://app.geociudadanos.org/assets/css/map.css).

I'm not sure, but `run.next` is the problem, it never runs the function passed to it.

**Comment by IAmJulianAcosta** [comment]
Just tried this, in order to be 100% sure:

```
_waitForTransition() {
    return new Promise(resolve => {
      run.next(() => {
	      alert ("A");
        let duration = 0;

        if (this.get('isAnimated')) {
          duration = this.get('transitionDuration');
        }

        run.later(this, resolve, duration);
      });
    },
    );
  },
```

I never saw the alert

**Comment by jgwhite** [comment]
@IAmJulianAcosta hmm… `run.next` comes direct from Ember. Do you see the same behaviour on Ember 2.5.x ?

**Comment by IAmJulianAcosta** [comment]
Tried with 2.4, 2.5, and 2.6, same result

**Comment by jgwhite** [comment]
Very strange. I think the best best will be to check this out via a screenhero session. Are you available any time soon?

**Comment by IAmJulianAcosta** [comment]
I'll message you in ember slack :)

**Comment by jgwhite** [comment]
So this turned out to be a very interesting issue where a library @IAmJulianAcosta was using (Date.js) was overriding `Date.now` to return a string representation. This is a problem because Backburner uses `Date.now` internally and expects integer representations.

**Comment by IAmJulianAcosta** [comment]
Not sure if the problem was [date.js](http://www.datejs.com/) or [date format](https://gist.github.com/eralston/968809), but after I migrated to [moment.js](http://momentjs.com), it worked as intended, thanks again @jgwhite !
